jg_platform:
    resource: "@JGPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform


# On inclut également les routes de notre CoreBundle, sans préfixe
jg_core:
    resource: "@JGCoreBundle/Resources/config/routing.yml"



