jg_platform_homepage:
    path:     /
    defaults: { _controller: JGPlatformBundle:Default:index }



jg_platform_page_1:
    path:    /page-1
    defaults: { _controller: JGPlatformBundle:Formulaire:page1 }

jg_platform_page_2:
    path:    /page-2
    defaults: { _controller: JGPlatformBundle:Formulaire:page2 }
